# vagrant plugin install vagrant-hostmanager

Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
    ### DB vm  ####
    config.vm.define "db01" do |db01|
        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", type: "static", ip: "192.168.56.15"
        db01.ssh.insert_key = false
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "600"
        end

        db01.vm.provision "shell", inline: <<-SHELL
            sudo yum update -y
            sudo yum install epel-release -y
            sudo yum install git mariadb-server -y
            sudo systemctl enable --now mariadb
        SHELL
    end
    
    ### Memcache vm  #### 
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", type: "static", ip: "192.168.56.14"
        mc01.ssh.insert_key = false
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "600"
        end

        mc01.vm.provision "shell", inline: <<-SHELL
            sudo yum update -y
            sudo yum install epel-release -y
            sudo yum install memcached -y
            sudo systemctl enable --now memcached
        SHELL
    end
    
    ### RabbitMQ vm  ####
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", type: "static", ip: "192.168.56.13"
        rmq01.ssh.insert_key = false
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = "600"
        end

        rmq01.vm.provision "shell", inline: <<-SHELL
            sudo yum update -y
            sudo yum install epel-release -y
            sudo yum install wget -y
            cd /tmp/
            sudo dnf -y install centos-release-rabbitmq-38
            sudo dnf --enablerepo=centos-rabbitmq-38 -y install rabbitmq-server
            sudo systemctl enable --now rabbitmq-server
        SHELL
    end
    
    ### tomcat vm ###
    config.vm.define "app01" do |app01|
        app01.vm.box = "eurolinux-vagrant/centos-stream-9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", type: "static", ip: "192.168.56.12"
        app01.ssh.insert_key = false
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "800"
        end

        app01.vm.provision "shell", inline: <<-SHELL
            sudo yum update -y
            sudo yum install epel-release -y
            sudo yum install git maven wget -y
            sudo dnf -y install java-11-openjdk java-11-openjdk-devel
        SHELL
    end
     
    
    ### Nginx VM ###
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", type: "static", ip: "192.168.56.11"
        web01.ssh.insert_key = false
        web01.vm.provider "virtualbox" do |vb|
        vb.gui = true
            vb.memory = "800"
        end

        web01.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt upgrade -y
            sudo apt install nginx -y
        SHELL
    end
end